In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('E_Commerce_Data.csv')

In [3]:
df.head(5)

,Order_ID,Order_Date,Order_Status,CustomerID,Gender,Age,City,Country,Subscription Status,Category,Item_Purchased,Quantity,Purchase_Amount,Discount Applied,Shipping_Cost,Payment Method,Previous Purchases,Frequency of Purchases,Ship_Mode,Review Rating
0,405-8078784-5731545,4/30/2022,Cancelled,17850.0,Male,55,Tokyo,Japan,Yes,Beauty,Face Wash,6,236.53,Yes,171.35,Venmo,14,Fortnightly,Same Day,3.1
1,171-9198151-1101146,4/30/2022,Shipped - Delivered to Buyer,17850.0,Male,19,New York,United States,Yes,Sports,Basketball,6,432.79,Yes,209.13,Cash,2,Fortnightly,Standard,3.1
2,404-0687676-7273146,4/30/2022,Shipped,17850.0,Male,50,Mexico City,Mexico,Yes,Toys,Doll,8,517.02,Yes,278.31,Credit Card,23,Weekly,Same Day,3.1
3,403-9615377-8133951,4/30/2022,Cancelled,17850.0,Male,21,Mumbai,India,Yes,Beauty,Face Wash,6,373.19,Yes,73.08,PayPal,49,Weekly,Standard,3.5
4,407-1069790-7240320,4/30/2022,Shipped,17850.0,Male,45,SÃ£o Paulo,Brazil,Yes,Clothing,T-Shirt,6,444.80,Yes,149.27,PayPal,31,Annually,Standard,2.7

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                3900 non-null   str
 1   Order_Date              3900 non-null   str
 2   Order_Status            3900 non-null   str
 3   CustomerID              2749 non-null   float64
 4   Gender                  3900 non-null   str
 5   Age                     3900 non-null   int64
 6   City                    3900 non-null   str
 7   Country                 3900 non-null   str
 8   Subscription Status     3900 non-null   str
 9   Category                3900 non-null   str
 10  Item_Purchased          3900 non-null   str
 11  Quantity                3900 non-null   int64
 12  Purchase_Amount         3900 non-null   float64
 13  Discount Applied        3900 non-null   str
 14  Shipping_Cost           3900 non-null   float64
 15  Payment Method          3900 non-null   str
 16  Previous Purchases      3900 non-null   int64
 17  Frequency of Purchases  3900 non-null   str
 18  Ship_Mode               3900 non-null   str
 19  Review Rating           3853 non-null   float64
dtypes: float64(4), int64(3), str(13)
memory usage: 609.5 KB

In [5]:
df.describe()

,CustomerID,Age,Quantity,Purchase_Amount,Shipping_Cost,Previous Purchases,Review Rating
count,2749.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3853.000000
mean,15771.729720,44.068462,9.077692,439.633454,272.384297,25.351538,3.748637
std,1790.823497,15.207589,24.617346,151.357213,128.644765,14.447125,0.714889
min,12431.000000,18.000000,-24.000000,200.000000,50.120000,1.000000,2.500000
25%,14390.000000,31.000000,1.000000,308.062500,161.440000,13.000000,3.100000
50%,15862.000000,44.000000,3.000000,437.925000,269.210000,25.000000,3.700000
75%,17841.000000,57.000000,9.000000,569.195000,382.685000,38.000000,4.400000
max,18229.000000,70.000000,600.000000,1276.910000,499.930000,50.000000,5.000000

In [6]:
df.isnull().sum()

Order_ID                     0
Order_Date                   0
Order_Status                 0
CustomerID                1151
Gender                       0
Age                          0
City                         0
Country                      0
Subscription Status          0
Category                     0
Item_Purchased               0
Quantity                     0
Purchase_Amount              0
Discount Applied             0
Shipping_Cost                0
Payment Method               0
Previous Purchases           0
Frequency of Purchases       0
Ship_Mode                    0
Review Rating               47
dtype: int64

In [7]:
df = df[df['CustomerID'].notna()]

In [8]:
df.isnull().sum()

Order_ID                   0
Order_Date                 0
Order_Status               0
CustomerID                 0
Gender                     0
Age                        0
City                       0
Country                    0
Subscription Status        0
Category                   0
Item_Purchased             0
Quantity                   0
Purchase_Amount            0
Discount Applied           0
Shipping_Cost              0
Payment Method             0
Previous Purchases         0
Frequency of Purchases     0
Ship_Mode                  0
Review Rating             47
dtype: int64

In [9]:
df['Review Rating'] = df['Review Rating'].fillna(df['Review Rating'].mean())

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['order_id', 'order_date', 'order_status', 'customerid', 'gender', 'age',
       'city', 'country', 'subscription_status', 'category', 'item_purchased',
       'quantity', 'purchase_amount', 'discount_applied', 'shipping_cost',
       'payment_method', 'previous_purchases', 'frequency_of_purchases',
       'ship_mode', 'review_rating'],
      dtype='str')

In [11]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [12]:
df['month'] = df['order_date'].dt.to_period('M')
df['month'] = df['month'].astype(str)

In [13]:
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Annually' : 365,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Monthly' : 30,
    'Every 3 Months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df['purchase_frequency_days']

0        14
1        14
2         7
3         7
4       365
       ...
3895      7
3896     14
3897     90
3898      7
3899     90
Name: purchase_frequency_days, Length: 2749, dtype: int64

In [16]:
import mysql.connector
from sqlalchemy import create_engine

conn = mysql.connector.connect(
    host="localhost",      # same as Workbench
    user="root",           # your username
    password="Nadia@1008",
    database="ECommerce"
)

In [17]:
engine = create_engine(
    "mysql+mysqlconnector://root:Nadia%401008@localhost:3306/ECommerce"
)
df.to_sql(
    name="sales",       # table name in SQL
    con=engine,
    if_exists="replace",   # or "append"
    index=False
)

-1